// Generates public/banner.svg: assets/tiling.svg faded behind a vignette,
// with assets/banner.svg (the wordmark and tagline, from wordmark.mjs) on
// top. Shown at the top of the welcome document. One step of generate.mjs,
// run after tiling.mjs and wordmark.mjs have written those files.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = new URL('../../', import.meta.url);

export function generateBanner() {
  const tiling = readFileSync(fileURLToPath(new URL('assets/tiling.svg', root)), 'utf8');
  const wordmark = readFileSync(fileURLToPath(new URL('assets/banner.svg', root)), 'utf8');

  const width = 1600;
  const height = 400;
  const background = '#0a0a0a';
  /** How visible the tiling is behind the vignette. */
  const tilingOpacity = 0.25;
  /** The vignette: a blurred rect, darker than the tiling but not fully opaque, over the wordmark. */
  const vignette = { x: 140, y: 40, width: 1320, height: 320, blur: 110, opacity: 0.95 };

  const innerOf = (svg) => svg.replace(/^<\?xml[^>]*>\s*/, '').replace(/<svg\b[^>]*>/, '').replace(/<\/svg>\s*$/, '');

  const banner = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}">
  <!-- Generated by scripts/logo/banner.mjs. -->
  <title>Easy Marko</title>
  <filter id="soften" x="-50%" y="-100%" width="200%" height="300%"><feGaussianBlur stdDeviation="${vignette.blur}"/></filter>
  <rect width="${width}" height="${height}" fill="${background}"/>
  <g opacity="${tilingOpacity}">
${innerOf(tiling)}
  </g>
  <rect x="${vignette.x}" y="${vignette.y}" width="${vignette.width}" height="${vignette.height}" fill="#000" fill-opacity="${vignette.opacity}" filter="url(#soften)"/>
${innerOf(wordmark)}
</svg>
`;

  writeFileSync(fileURLToPath(new URL('public/banner.svg', root)), banner);
  console.log('public/banner.svg');
}
