// Generates public/banner.svg: black with assets/tiling.svg, translucent, behind a vignette,
// with assets/banner.svg (the wordmark and tagline, from wordmark.mjs) on
// top. Shown at the top of the welcome document. One step of generate.mjs,
// run after tiling.mjs and wordmark.mjs have written those files.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = new URL('../../', import.meta.url);

/** The banner's size in its own units, which the wordmark in assets/banner.svg shares. */
export const bannerSize = { width: 1600, height: 400 };

const innerOf = (svg) => svg.replace(/^<\?xml[^>]*>\s*/, '').replace(/<svg\b[^>]*>/, '').replace(/<\/svg>\s*$/, '');

export function generateBanner() {
  const tiling = readFileSync(fileURLToPath(new URL('assets/tiling.svg', root)), 'utf8');
  const wordmark = readFileSync(fileURLToPath(new URL('assets/banner.svg', root)), 'utf8');

  const { width, height } = bannerSize;
  /** The corner radius the whole banner is clipped to. */
  const cornerRadius = 24;

  const banner = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}">
  <!-- Generated by scripts/logo/banner.mjs. -->
  <title>Easy Marko</title>
  <clipPath id="rounded"><rect width="${width}" height="${height}" rx="${cornerRadius}"/></clipPath>
  <g clip-path="url(#rounded)">
${bannerLayers({ width, height, tiling, wordmark })}
  </g>
</svg>
`;

  writeFileSync(fileURLToPath(new URL('public/banner.svg', root)), banner);
  console.log('public/banner.svg');
}

/**
 * The banner's layers, `width` by `height`: translucent black with `tiling` (an SVG of that size),
 * then the vignette and `wordmark` (an SVG in banner units), placed by `transform`.
 */
export function bannerLayers({ width, height, tiling, wordmark, transform }) {
  /** How opaque the background (black, tiling and one vignette) is, so the page shows through. */
  const backgroundOpacity = 0.75;
  /** How visible the tiling is against the black. */
  const tilingOpacity = 0.35;
  /**
   * The vignette, in banner units: a blurred black rect behind the wordmark. Drawn twice at this
   * opacity, once inside the translucent background and once above it, so the wordmark stays legible.
   */
  const vignette = { x: 140, y: 40, width: 1320, height: 320, blur: 110, opacity: 0.7 };

  const place = (content) => (transform ? `<g transform="${transform}">${content}</g>` : content);
  const vignetteRect = place(
    `<rect x="${vignette.x}" y="${vignette.y}" width="${vignette.width}" height="${vignette.height}" fill="#000" fill-opacity="${vignette.opacity}" filter="url(#soften)"/>`,
  );

  return `  <filter id="soften" x="-50%" y="-100%" width="200%" height="300%"><feGaussianBlur stdDeviation="${vignette.blur}"/></filter>
  <g opacity="${backgroundOpacity}">
  <rect width="${width}" height="${height}" fill="#000"/>
  <g opacity="${tilingOpacity}">
${innerOf(tiling)}
  </g>
  ${vignetteRect}
  </g>
  ${vignetteRect}
${place(innerOf(wordmark))}`;
}
