// Generates public/banner.svg: black with assets/tiling.svg, translucent, behind a vignette,
// with assets/banner.svg (the wordmark and tagline, from wordmark.mjs) on
// top. Shown at the top of the welcome document. One step of generate.mjs,
// run after tiling.mjs and wordmark.mjs have written those files.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = new URL('../../', import.meta.url);

export function generateBanner() {
  const tiling = readFileSync(fileURLToPath(new URL('assets/tiling.svg', root)), 'utf8');
  const wordmark = readFileSync(fileURLToPath(new URL('assets/banner.svg', root)), 'utf8');

  const width = 1600;
  const height = 400;
  /** How opaque the background (black, tiling and one vignette) is, so the page shows through. */
  const backgroundOpacity = 0.75;
  /** How visible the tiling is against the black. */
  const tilingOpacity = 0.35;
  /**
   * The vignette: a blurred black rect behind the wordmark. Drawn twice at this opacity, once
   * inside the translucent background and once above it, so the wordmark stays legible.
   */
  const vignette = { x: 140, y: 40, width: 1320, height: 320, blur: 110, opacity: 0.7 };

  const innerOf = (svg) => svg.replace(/^<\?xml[^>]*>\s*/, '').replace(/<svg\b[^>]*>/, '').replace(/<\/svg>\s*$/, '');
  const vignetteRect = `<rect x="${vignette.x}" y="${vignette.y}" width="${vignette.width}" height="${vignette.height}" fill="#000" fill-opacity="${vignette.opacity}" filter="url(#soften)"/>`;

  const banner = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}">
  <!-- Generated by scripts/logo/banner.mjs. -->
  <title>Easy Marko</title>
  <filter id="soften" x="-50%" y="-100%" width="200%" height="300%"><feGaussianBlur stdDeviation="${vignette.blur}"/></filter>
  <g opacity="${backgroundOpacity}">
  <rect width="${width}" height="${height}" fill="#000"/>
  <g opacity="${tilingOpacity}">
${innerOf(tiling)}
  </g>
  ${vignetteRect}
  </g>
  ${vignetteRect}
${innerOf(wordmark)}
</svg>
`;

  writeFileSync(fileURLToPath(new URL('public/banner.svg', root)), banner);
  console.log('public/banner.svg');
}
