// Generates public/icon.svg: the logo's E and M, outlined from Figtree at
// weight 800, on a rounded square. One step of generate.mjs; app-icons.mjs
// rasterises the result into the PWA's PNG icons.
//
// The background is the dark theme's page colour, a little lighter at the top
// and darker at the bottom. The letters are shaded with top-to-bottom gradients, the M casts a soft
// shadow over the E, and the E's blue glows onto the M where its bars meet it.

import { lightDarkToken } from '../../src/lib/css-tokens.ts';
import { readProjectFile, writeProjectFile } from './files.mjs';
import { E, accent, eCommands, light, loadFont, pathData, round, shape } from './glyphs.mjs';

/** `colour` (#rrggbb) moved `amount` of the way to `target` (#rrggbb). */
function mix(colour, target, amount) {
  const channels = (hex) => [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16));
  const [from, to] = [channels(colour), channels(target)];
  return `#${from.map((c, i) => Math.round(c + (to[i] - c) * amount).toString(16).padStart(2, '0')).join('')}`;
}

/** Gradient stops as [offset, colour], top to bottom. */
const eShade = [
  [0, '#4777ef'],
  [0.55, accent],
  [0.93, '#3c6dde'],
  [1, '#335ac6'],
];
const mShade = [
  [0, light],
  [0.58, '#eaeaea'],
  [0.9, '#d7d7d7'],
  [1, '#c6c6c6'],
];
const shadow = { colour: '#070c1c', opacity: 0.36, blur: 26 };
const glow = { opacity: 0.45, blur: 20 };

function gradient(id, stops, top, bottom) {
  const stopTags = stops.map(([offset, colour]) => `<stop offset="${offset}" stop-color="${colour}"/>`).join('');
  return `<linearGradient id="${id}" gradientUnits="userSpaceOnUse" x1="0" y1="${top}" x2="0" y2="${bottom}">${stopTags}</linearGradient>`;
}

/** A Gaussian blur whose region is the whole icon, so it never cuts off. */
function blur(id, deviation) {
  return `<filter id="${id}" filterUnits="userSpaceOnUse" x="0" y="0" width="512" height="512"><feGaussianBlur stdDeviation="${deviation}"/></filter>`;
}

export async function generateIcon() {
  const font = await loadFont();
  const background = lightDarkToken(readProjectFile('src/styles/tokens.css'), '--color-bg').dark;
  const backgroundShade = [
    [0, mix(background, '#ffffff', 0.03)],
    [1, mix(background, '#000000', 0.2)],
  ];

  // The E and M 384 wide, centred on a 512 square. The E's bars end where the
  // M's left stem begins.
  const mCommands = shape(font, 'M', 800).glyphs[0].commands;
  /** Figtree's M stems span 68 to 794.6. */
  const mLeft = 68;
  const mRight = 794.6;
  const logoWidth = E.width + mRight - mLeft;
  const iconScale = 384 / logoWidth;
  const iconSize = iconScale * 1000;
  const iconLeft = 256 - (logoWidth * iconScale) / 2;
  const iconBaseline = 256 + (700 * iconScale) / 2;
  const top = round(iconBaseline - 700 * iconScale);
  const bottom = round(iconBaseline);

  const ePath = pathData(eCommands(-E.left), iconLeft, iconBaseline, iconSize);
  const mPath = pathData(mCommands, iconLeft + (E.width - mLeft) * iconScale, iconBaseline, iconSize);

  // The glow: blurred blue ellipses centred just left of the seam between the
  // letters, at each of the E's bars, clipped to the M. The middle one is
  // narrower, as that bar ends in a point short of the M.
  const seam = iconLeft + E.width * iconScale;
  const barCentre = (E.bar / 2) * iconScale;
  const middleCentre = iconBaseline - ((E.middle.bottom + E.middle.top) / 2) * iconScale;
  const glowSpots = [
    { cx: seam - 36, cy: top + barCentre, rx: 45, ry: 50 },
    { cx: seam - 14, cy: middleCentre, rx: 18, ry: 50 },
    { cx: seam - 36, cy: bottom - barCentre, rx: 45, ry: 50 },
  ]
    .map(({ cx, cy, rx, ry }) => `<ellipse cx="${round(cx)}" cy="${round(cy)}" rx="${rx}" ry="${ry}"/>`)
    .join('');

  const icon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
  <!-- Generated by scripts/logo/icon.mjs. The E and M are 384 wide, leaving a 64 margin at the sides. -->
  <defs>
    ${gradient('background', backgroundShade, 0, 512)}
    ${gradient('e-shade', eShade, top, bottom)}
    ${gradient('m-shade', mShade, top, bottom)}
    ${blur('shadow', shadow.blur)}
    ${blur('glow', glow.blur)}
    <clipPath id="m-clip"><path d="${mPath}"/></clipPath>
  </defs>
  <rect width="512" height="512" rx="96" fill="url(#background)"/>
  <path d="${ePath}" fill="url(#e-shade)"/>
  <path d="${mPath}" fill="${shadow.colour}" opacity="${shadow.opacity}" filter="url(#shadow)"/>
  <path d="${mPath}" fill="url(#m-shade)"/>
  <g clip-path="url(#m-clip)"><g fill="${accent}" opacity="${glow.opacity}" filter="url(#glow)">${glowSpots}</g></g>
</svg>
`;
  writeProjectFile('public/icon.svg', icon);
}
