// Generates public/icon.svg: the logo's E and M, outlined from Figtree at
// weight 800, on a rounded square. One step of generate.mjs; app-icons.mjs
// rasterises the result into the PWA's PNG icons.

import { writeFileSync } from 'node:fs';
import { E, accent, background, eCommands, light, loadFont, pathData, shape } from './glyphs.mjs';

const root = new URL('../../', import.meta.url);

export async function generateIcon() {
  const font = await loadFont();

  // The E and M 384 wide, centred on a 512 square. The E's bars end where the
  // M's left stem begins.
  const mCommands = shape(font, 'M', 800).glyphs[0].commands;
  /** Figtree's M stems span 68 to 794.6. */
  const mLeft = 68;
  const mRight = 794.6;
  const logoWidth = E.width + mRight - mLeft;
  const iconScale = 384 / logoWidth;
  const iconSize = iconScale * 1000;
  const iconLeft = 256 - (logoWidth * iconScale) / 2;
  const iconBaseline = 256 + (700 * iconScale) / 2;

  const icon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
  <!-- Generated by scripts/logo/icon.mjs. The E and M are 384 wide, leaving a 64 margin at the sides. -->
  <rect width="512" height="512" rx="96" fill="${background}"/>
  <path d="${pathData(eCommands(-E.left), iconLeft, iconBaseline, iconSize)}" fill="${accent}"/>
  <path d="${pathData(mCommands, iconLeft + (E.width - mLeft) * iconScale, iconBaseline, iconSize)}" fill="${light}"/>
</svg>
`;
  writeFileSync(new URL('public/icon.svg', root), icon);
  console.log('public/icon.svg');
}
