// Generates assets/tiling.svg: the logo's E and M tiled at different
// rotations, at full opacity and colour. One step of generate.mjs; banner.mjs
// fades this and layers the wordmark on top to build the public banner.
// og-image.mjs builds its own, larger tiling with tilingSvg().

import { bannerSize } from './banner.mjs';
import { writeProjectFile } from './files.mjs';
import { E } from './glyphs.mjs';

export function generateTiling() {
  const { width, height } = bannerSize;
  writeProjectFile('assets/tiling.svg', tilingSvg({ width, height, cell: height / 3 }));
}

/**
 * The tiling as an SVG `width` by `height`, in square cells of side `cell`.
 * The grid is centred, and tiles that don't fit are clipped at the edges.
 */
export function tilingSvg({ width, height, cell }) {
  /** Letter size in the cell; the rest is the gap between letters. */
  const glyph = (cell * 44) / 48;
  const colour = { e: '#1f5dff', m: '#888' };
  const seed = 7;

  const round = (value) => +value.toFixed(1);
  /** Scales a letter from its 700-unit box to the glyph size. */
  const scale = +(glyph / 700).toFixed(5);

  // The letters are the logo's (icon.mjs), from Figtree at weight 800 in font
  // units, drawn in a 700-unit box centred on the origin.
  /** The E's top and bottom bars, which are also the M's strokes. */
  const { bar, stem } = E;

  // The E's bars reach the right edge. Its stem and bar thicknesses are the
  // logo's; the middle bar's point stops a bar's thickness short of the edge.
  const middle = { top: round(350 - E.middle.top), bottom: round(350 - E.middle.bottom) };
  const taper = (middle.bottom - middle.top) / 2;
  const tip = 350 - bar;
  const e = [
    `M-350-350H350v${bar}H${round(-350 + stem)}V${middle.top}`,
    `H${round(tip - taper)}L${round(tip)} ${round(middle.top + taper)}L${round(tip - taper)} ${middle.bottom}`,
    `H${round(-350 + stem)}V${350 - bar}H350v${bar}H-350z`,
  ].join('');

  // The M's legs and the flat tops beside its diagonals are as wide as the E's
  // bars. The diagonals keep Figtree's slope and vertical thickness.
  const slope = 276 / 186.6;
  const diagonal = 269.8;
  const outerPoint = -350 + (350 - bar) * slope;
  const innerPoint = outerPoint + diagonal;
  const innerLeg = innerPoint - (350 - bar) * slope;
  const m = [
    `M-350 350V-350h${bar}L0 ${round(outerPoint)}L${350 - bar} -350H350V350H${350 - bar}`,
    `V${round(innerLeg)}L0 ${round(innerPoint)}L${-350 + bar} ${round(innerLeg)}V350z`,
  ].join('');

  let state = seed;
  const random = () => (state = (state * 1103515245 + 12345) % 2147483648) / 2147483648;

  const rows = Math.ceil(height / cell - 1e-9);
  const cols = Math.ceil(width / cell - 1e-9);
  const offset = { x: (width - cols * cell) / 2, y: (height - rows * cell) / 2 };
  const rotations = [];
  const tiles = [];
  for (let row = 0; row < rows; row++) {
    rotations.push([]);
    for (let col = 0; col < cols; col++) {
      const letter = (row + col) % 2 ? 'm' : 'e';
      // Tiles two columns or rows apart hold the same letter; they don't share a rotation.
      const taken = [rotations[row][col - 2], rotations[row - 2]?.[col]];
      const options = [0, 90, 180, 270].filter((angle) => !taken.includes(angle));
      const angle = options[Math.floor(random() * options.length)];
      rotations[row].push(angle);
      const rotate = angle ? ` rotate(${angle})` : '';
      const transform = `translate(${offset.x + col * cell + cell / 2} ${offset.y + row * cell + cell / 2})${rotate} scale(${scale})`;
      tiles.push(`  <use href="#${letter}" transform="${transform}"/>`);
    }
  }

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}">
  <!-- Generated by scripts/logo/tiling.mjs. A tiling of the Easy Marko E and M at different rotations. -->
  <defs>
    <path id="e" fill="${colour.e}" d="${e}"/>
    <path id="m" fill="${colour.m}" d="${m}"/>
  </defs>
${tiles.join('\n')}
</svg>
`;
}
