// Generates assets/banner.svg: the "#EASYMARKO" wordmark (using the logo's E)
// over "Markdown editor", both outlined from Figtree, on a transparent
// background so callers can lay their own background behind it. One step of
// generate.mjs; banner.mjs and og-image.mjs both build on the result.

import { bannerSize } from './banner.mjs';
import { writeProjectFile } from './files.mjs';
import { accent, light, loadFont, textPaths } from './glyphs.mjs';

export async function generateWordmark() {
  const font = await loadFont();

  // The wordmark over the tagline, centred on the banner.
  const { width, height } = bannerSize;
  const titleSize = 177;
  const taglineSize = 85;
  /** From the title's baseline to the tagline's. */
  const lineGap = 115;
  const capHeight = 700;
  const blockHeight = (capHeight * titleSize) / 1000 + lineGap;
  const titleBaseline = +(height / 2 - blockHeight / 2 + (capHeight * titleSize) / 1000).toFixed(2);

  const title = textPaths(font, '#EASYMARKO', 800, titleSize, width / 2, titleBaseline, (char, i) =>
    char === '#' ? `fill="${accent}" fill-opacity="0.5"` : i < 5 ? `fill="${accent}"` : `fill="${light}"`,
    // Figtree's K and O are set a little loose at this weight, and S and Y
    // leave an optical gap where their strokes converge.
    { Y: -22.6, O: -50 },
  );
  const tagline = textPaths(font, 'markdown editor', 500, taglineSize, width / 2, titleBaseline + lineGap, () => 'fill="#e5e5e5"');

  const banner = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}">
  <!-- Generated by scripts/logo/wordmark.mjs. The wordmark and tagline, transparent so callers can lay their own background behind it. -->
  <title>Easy Marko</title>
${title}
${tagline}
</svg>
`;
  writeProjectFile('assets/banner.svg', banner);
}
