// Generates assets/tiling.svg: the logo's E and M tiled at different
// rotations, at full opacity and colour. scripts/combine-banner.mjs fades it
// and layers the wordmark on top to build the public banner.
//
//   node scripts/banner.mjs

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const file = fileURLToPath(new URL('../assets/tiling.svg', import.meta.url));

const width = 1600;
const height = 400;
const cell = height / 3;
/** Letter size in the cell; the rest is the gap between letters. */
const glyph = (cell * 44) / 48;
const colour = { e: '#1f5dff', m: '#888' };
const seed = 7;

const round = (value) => +value.toFixed(1);
/** Scales a letter from its 700-unit box to the glyph size. */
const scale = +(glyph / 700).toFixed(5);

// The letters are the logo's (scripts/logo.mjs), from Figtree at weight 800 in
// font units, drawn in a 700-unit box centred on the origin.
/** The E's top and bottom bars, which are also the M's strokes. */
const bar = 147.6;

// The E's bars reach the right edge. Its stem and bar thicknesses are the
// logo's; the middle bar's point stops a bar's thickness short of the edge.
const stem = 160.8;
const middle = { top: -74.4, bottom: 69.2 };
const taper = (middle.bottom - middle.top) / 2;
const tip = 350 - bar;
const e = [
  `M-350-350H350v${bar}H${round(-350 + stem)}V${middle.top}`,
  `H${round(tip - taper)}L${round(tip)} ${round(middle.top + taper)}L${round(tip - taper)} ${middle.bottom}`,
  `H${round(-350 + stem)}V${350 - bar}H350v${bar}H-350z`,
].join('');

// The M's legs and the flat tops beside its diagonals are as wide as the E's
// bars. The diagonals keep Figtree's slope and vertical thickness.
const slope = 276 / 186.6;
const diagonal = 269.8;
const outerPoint = -350 + (350 - bar) * slope;
const innerPoint = outerPoint + diagonal;
const innerLeg = innerPoint - (350 - bar) * slope;
const m = [
  `M-350 350V-350h${bar}L0 ${round(outerPoint)}L${350 - bar} -350H350V350H${350 - bar}`,
  `V${round(innerLeg)}L0 ${round(innerPoint)}L${-350 + bar} ${round(innerLeg)}V350z`,
].join('');

let state = seed;
const random = () => (state = (state * 1103515245 + 12345) % 2147483648) / 2147483648;

const rows = height / cell;
const cols = width / cell;
const rotations = [];
const tiles = [];
for (let row = 0; row < rows; row++) {
  rotations.push([]);
  for (let col = 0; col < cols; col++) {
    const letter = (row + col) % 2 ? 'm' : 'e';
    // Tiles two columns or rows apart hold the same letter; they don't share a rotation.
    const taken = [rotations[row][col - 2], rotations[row - 2]?.[col]];
    const options = [0, 90, 180, 270].filter((angle) => !taken.includes(angle));
    const angle = options[Math.floor(random() * options.length)];
    rotations[row].push(angle);
    const rotate = angle ? ` rotate(${angle})` : '';
    const transform = `translate(${col * cell + cell / 2} ${row * cell + cell / 2})${rotate} scale(${scale})`;
    tiles.push(`  <use href="#${letter}" transform="${transform}"/>`);
  }
}

writeFileSync(
  file,
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}">
  <!-- Generated by scripts/banner.mjs. A tiling of the Easy Marko E and M at different rotations. -->
  <defs>
    <path id="e" fill="${colour.e}" d="${e}"/>
    <path id="m" fill="${colour.m}" d="${m}"/>
  </defs>
${tiles.join('\n')}
</svg>
`,
);
console.log('assets/tiling.svg');
