// Generates public/welcome-banner.svg, the banner at the top of the welcome
// document: the logo's E and M squared up and tiled at different rotations.
//
//   node scripts/banner.mjs

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const file = fileURLToPath(new URL('../public/welcome-banner.svg', import.meta.url));

const width = 720;
const height = 144;
const cell = 48;
/** Letter size in the cell; the rest is the gap between letters. */
const glyph = 44;
/** Stroke width, in the letters' 192-unit box. */
const stroke = 46;
/** Fill opacity of each letter. */
const opacity = { e: 0.45, m: 0.3 };
const seed = 7;

const round = (value) => +value.toFixed(1);

// The letters are drawn in a 192-unit box centred on the origin.
const gap = (192 - 3 * stroke) / 2;
const e = [
  `M-96-96H96v${stroke}H${-96 + stroke}v${round(gap)}`,
  `H${round(40 - stroke / 2)}l${stroke / 2} ${stroke / 2} ${-stroke / 2} ${stroke / 2}`,
  `H${-96 + stroke}v${round(gap)}H96v${stroke}H-96z`,
].join('');

// The M's diagonals keep a 1.25 slope and are a little thicker than its legs.
const slope = 1.25;
const outerPoint = -96 + (96 - stroke) * slope;
const innerPoint = outerPoint + (stroke * 50) / 48 / Math.cos(Math.atan(slope));
const innerLeg = innerPoint - (96 - stroke) * slope;
const m = [
  `M-96 96V-96h${stroke}L0 ${round(outerPoint)}L${96 - stroke} -96H96V96H${96 - stroke}`,
  `V${round(innerLeg)}L0 ${round(innerPoint)}L${-96 + stroke} ${round(innerLeg)}V96z`,
].join('');

let state = seed;
const random = () => (state = (state * 1103515245 + 12345) % 2147483648) / 2147483648;

const rows = height / cell;
const cols = width / cell;
const rotations = [];
const tiles = [];
for (let row = 0; row < rows; row++) {
  rotations.push([]);
  for (let col = 0; col < cols; col++) {
    const letter = (row + col) % 2 ? 'm' : 'e';
    // Tiles two columns or rows apart hold the same letter; they don't share a rotation.
    const taken = [rotations[row][col - 2], rotations[row - 2]?.[col]];
    const options = [0, 90, 180, 270].filter((angle) => !taken.includes(angle));
    const angle = options[Math.floor(random() * options.length)];
    rotations[row].push(angle);
    const rotate = angle ? ` rotate(${angle})` : '';
    const transform = `translate(${col * cell + cell / 2} ${row * cell + cell / 2})${rotate} scale(${+(glyph / 192).toFixed(4)})`;
    tiles.push(`  <use href="#${letter}" transform="${transform}"/>`);
  }
}

writeFileSync(
  file,
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}">
  <!-- Generated by scripts/banner.mjs. Shown in the welcome document on any background, so only translucent grey and the accent. -->
  <title>A tiling of the Easy Marko E and M at different rotations</title>
  <defs>
    <path id="e" fill="#4c7bf4" fill-opacity="${opacity.e}" d="${e}"/>
    <path id="m" fill="#888" fill-opacity="${opacity.m}" d="${m}"/>
  </defs>
${tiles.join('\n')}
</svg>
`,
);
